### PR TITLE
Option for running a read only replica in Docker container

### PR DESCRIPTION
**Pull request by a-belyaev**
https://github.com/tarantool/docker/issues/49

### CODE REVIEW

**Comment by Totktonada** [comment]
@avtikhon Please, squash and update commits according to the new repository structure.

Please also ensure that all boolean box.cfg() options are added in the same way (see PR #153).

**Comment by Totktonada** [comment]
Looks related to #214.

**Comment by sergos** [comment]
@ylobankov please proceed with review

**Comment by kyukhin** [comment]
Ticket was closed, see the reason.

**Pull request closed without merging**
