### PR TITLE
+ldecnumber

### PR DESCRIPTION
**Pull request by parihaaraka**
if you don't mind :)

### CODE REVIEW

**Comment by olegrok** [comment]
Why do you use direct link to rockspec instead simple `lua rocks install ldecnumber`?

Also try to avoid scm and specify version explicitly.

Finally, we should discuss is it really needed in 2.x images?
decimal type should be included in next 2.2 release (https://github.com/tarantool/tarantool/issues/692) therefore I think it can be mixed in future.

**Comment by parihaaraka** [comment]
That is the only recommended way of ldecNumber installation I guess. If
official package is ok then I don't see the reason why the tarantool's one
exists.
2.x images are lack of decimals support for now.
As for version, I believe ldecNumber has been frozen forever.

сб, 15 июня 2019 г. в 7:46, Oleg Babin <notifications@github.com>:

**Comment by olegrok** [comment]
> 2.x images are lack of decimals support for now.

https://github.com/tarantool/tarantool/commit/3ab387a45e52ed01059b727596b35b8efad0b460

Now tarantool 2.2 supports decimal. Let's remove it from 2.x images.

**Comment by Totktonada** [comment]
@avtikhon It has sense for tarantool versions, where 'decimal' type is not supported. Can you update the PR accordingly?

**Comment by avtikhon** [comment]
> @avtikhon It has sense for tarantool versions, where 'decimal' type is not supported. Can you update the PR accordingly?

Right, I've checked Tarantool releases:
````
for rel in 1.10 2.1 2.2 2.3 2.4 2.5 master ; do res=`git log origin/$rel | grep "decimal: expose decimal type to lua"` ; echo "$rel: $res" ; done
1.10: 
2.1: 
2.2:     decimal: expose decimal type to lua.
2.3:     decimal: expose decimal type to lua.
2.4:     decimal: expose decimal type to lua.
2.5:     decimal: expose decimal type to lua.
master:     decimal: expose decimal type to lua.
```
and tags:
```
for rel in 2.2.0 2.2.1 2.2.2 2.2.3 ; do res=`git log $rel | grep "decimal: expose decimal type to lua"` ; echo "$rel: $res" ; done
2.2.0: 
2.2.1:     decimal: expose decimal type to lua.
2.2.2:     decimal: expose decimal type to lua.
2.2.3:     decimal: expose decimal type to lua.
```
According to the results added the ldecnumber installation.

**Comment by kyukhin** [comment]
decnumber is declining. We have onboard DECIMAL data type.

**Pull request closed without merging**
